### ISSUE TITLE
Function definition declaration split

### ISSUE THREAD

**Issue by okovtun** [Cepexa/TestRepo#1]
Здравствуйте Сереж!
Ну первое, я бы все таки разделил функции на прототип и реализацию, мне кажется так будет более "вежливо".

**Comment by Cepexa** [comment]
Здравствуйте, а так в принципе по алгоритму у вас замечаний нет?... может я баг какой нибудь не заметил, у Вас всё нормально отработало? пробовали?

**Comment by Cepexa** [comment]
Поправил... Но мне кажется, что для такого малюсенького проекта это лишнее

**Comment by okovtun** [comment]
> Здравствуйте, а так в принципе по алгоритму у вас замечаний нет?... может я баг какой нибудь не заметил, у Вас всё нормально отработало? пробовали?
Да, запускал, сначала без #include<iterator> не скомпилилось, но с ним все норм.
Если оба контейнера размером по 20 элементов, то все работает как часы, но если контейнеры задать небольшие, то кажись один раз разное содержимое выдало, потом проверял несколько раз, вроде норм, так что это и я мог не досмотреть.

**Comment by Cepexa** [comment]
спасибо за помощь!
