### ISSUE TITLE
input while

### ISSUE THREAD

**Issue by okovtun** [Cepexa/TestRepo#3]
Вот [здесь](https://github.com/Cepexa/TestRepo/blob/e2a1dd3754a1082907e63216372cf74a93d37e89/TestSolution/TestProject/TestProject.cpp#L35) лучше использовать do...while(...); 
В условии цикла должна быть Булева переменная, которая сбрасывается в начале итерации, и устанавливается в if-е, при необходимости.

**Comment by Cepexa** [comment]
Здесь я может быть не очень уловил вашу мысль, но мне кажется ещё одна переменная будет лишней.. эта конструкция свою функцию выполняет, зачем усложнять?

**Comment by okovtun** [comment]
Ну тогда хотя бы while(true) напишите, while(1) как-то аж глаз режет))

**Comment by okovtun** [comment]
А вообще я [такое](https://github.com/Cepexa/TestRepo/blob/3e9ef0d22c4f6f4fb7fa8b23313db1cdd8cccbee/TestSolution/TestProject/TestProject.cpp#L36) имел в виду.

**Comment by Cepexa** [comment]
поправил
