### ISSUE TITLE
static_cast

### ISSUE THREAD

**Issue by okovtun** [Cepexa/TestRepo#5]
Вот [здесь](https://github.com/Cepexa/TestRepo/blob/e2a1dd3754a1082907e63216372cf74a93d37e89/TestSolution/TestProject/TestProject.cpp#L61) лучше min, max сделайте типа size_t, тогда можно будет обойтись без static_cast.

**Comment by okovtun** [comment]
Хотя нет, потом на random() ругается.

**Comment by Cepexa** [comment]
я об этом думал, но там баг вылазит... size_t это unsigned int, соответственно при отрицательных значениях отрабатывает не корректно... отрицательные значения должны откидываться
